<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quantization-tables [
<!ELEMENT quantization-tables (table)+>
<!ELEMENT table (description , levels)>
<!ELEMENT description (CDATA)>
<!ELEMENT levels (CDATA)>
<!ATTLIST table slot ID #REQUIRED>
<!ATTLIST levels width CDATA #REQUIRED>
<!ATTLIST levels height CDATA #REQUIRED>
<!ATTLIST levels divisor CDATA #REQUIRED>
]>
<!--
  JPEG quantization tables.
-->
<quantization-tables>
  <table slot="0" alias="luminance">
    <description>Luminance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
       3,    2,    2,    3,    5,    8,   10,   12,
       2,    2,    3,    4,    5,   11,   11,   13,
       3,    2,    3,    5,    8,   11,   13,   11,
       3,    3,    4,    6,   10,   17,   15,   12,
       3,    4,    7,   11,   13,   21,   20,   15,
       5,    7,   10,   12,   15,   20,   21,   17,
       9,   12,   15,   17,   20,   23,   23,   19,
      14,   17,   18,   19,   21,   19,   20,   19
    </levels>
  </table>

  <table slot="1" alias="chrominance">
    <description>Chrominance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
        3,    3,    5,    9,   19,   19,   19,   19,
        3,    4,    5,   13,   19,   19,   19,   19,
        5,    5,   11,   19,   19,   19,   19,   19,
        9,   13,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19
    </levels>
  </table>
</quantization-tables>
